//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Content/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RacketControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RacketControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Racket"",
            ""id"": ""965f2b32-9854-4e98-9f4a-bb5e39aa42ea"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""40b84135-e539-40fb-9f73-e42372c81092"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b657ee67-c951-409c-a7f9-fbc0ec920977"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eeeb6ccc-48b5-4e21-acb3-f86892df4296"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Racket
        m_Racket = asset.FindActionMap("Racket", throwIfNotFound: true);
        m_Racket_Move = m_Racket.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Racket
    private readonly InputActionMap m_Racket;
    private List<IRacketActions> m_RacketActionsCallbackInterfaces = new List<IRacketActions>();
    private readonly InputAction m_Racket_Move;
    public struct RacketActions
    {
        private @RacketControls m_Wrapper;
        public RacketActions(@RacketControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Racket_Move;
        public InputActionMap Get() { return m_Wrapper.m_Racket; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RacketActions set) { return set.Get(); }
        public void AddCallbacks(IRacketActions instance)
        {
            if (instance == null || m_Wrapper.m_RacketActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RacketActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IRacketActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IRacketActions instance)
        {
            if (m_Wrapper.m_RacketActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRacketActions instance)
        {
            foreach (var item in m_Wrapper.m_RacketActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RacketActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RacketActions @Racket => new RacketActions(this);
    public interface IRacketActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
